include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    sort_child_properties_last: true
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: true
    prefer_single_quotes: true
    use_null_aware_elements: true

formatter:
  trailing_commas: preserve

exclude:
  - "**/*.g.dart"