name: word_game
description: A multiplayer word guessing game, inspired by Wordle.

publish_to: 'none'

version: 0.6.0+25

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../common/
  
  badges: ^2.0.2
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  duration: ^3.0.8
  fl_chart: ^0.61.0
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_native_splash: ^2.2.19
  flutter_neumorphic: ^3.2.0
  flutter_secure_storage: ^8.0.0
  flutter_spinkit: ^5.1.0
  flutter_web_frame: ^0.0.2
  fluttering_phrases: ^0.4.0
  get_it: ^7.2.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  linked_scroll_controller: ^0.2.0
  material_design_icons_flutter: ^6.0.7096
  mongo_dart: 0.8.2
  package_info_plus: ^3.0.3
  shared_preferences: ^2.0.13
  soundpool: ^2.3.0
  rest_client:
    git:
      url: https://github.com/alexobviously/rest_client
      ref: main
  url_launcher: ^6.0.19
  validators: ^3.0.0
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/words_alpha.txt
    - assets/words_common.txt
    - .env
    - assets/images/logo.png
    - assets/images/gpg_logo.png
    - assets/images/launcher_adaptive.png
    - assets/images/launcher_android.png
    - assets/images/launcher_ios.png
    - assets/images/github_white.png
    - assets/images/github_black.png
    - assets/sounds/

flutter_icons:
  image_path_android: "assets/images/launcher_android.png"
  image_path_ios: "assets/images/launcher_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#eeeeee"
  adaptive_icon_foreground: "assets/images/launcher_adaptive.png"