name: word_game
description: A multiplayer word guessing game, inspired by Wordle.

publish_to: 'none'

version: 0.2.2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../common/
  
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  duration: ^3.0.8
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_neumorphic: ^3.2.0
  flutter_spinkit: ^5.1.0
  fluttering_phrases: ^0.3.2
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  linked_scroll_controller: ^0.2.0
  material_design_icons_flutter: ^5.0.6595
  mongo_dart: ^0.7.4
  package_info_plus: ^1.3.0
  rest_client: ^2.0.1+6
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/words_alpha.txt
    - assets/words_common.txt
    - .env

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
