name: word_game_server
description: A simple command-line application.
version: 0.6.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  common:
      path: ../common/

  bloc: ^8.0.2
  dart_dotenv: ^1.0.1
  dbcrypt: ^2.0.0
  get_it: ^7.2.0
  jaguar_jwt: ^3.0.0
  mongo_dart: 0.8.2
  rxdart: ^0.27.3
  shelf: ^1.2.0
  shelf_cors_headers: ^0.1.2
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1
  uuid: ^3.0.5
  validators: ^3.0.0
  web_socket_channel: ^2.1.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.1
