name: word_game_server
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  bloc: ^8.0.2
  get_it: ^7.2.0
  jaguar_jwt: ^3.0.0
  shelf: ^1.2.0
  shelf_cors_headers: ^0.1.2
  shelf_router: ^1.1.2
  shelf_web_socket: ^1.0.1
  uuid: ^3.0.5
  validators: ^3.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  lints: ^1.0.0
