name: common
description: Common code shared between app and backend
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
