name: common
description: Common code shared between app and backend
version: 0.1.5
publish_to: 'none'

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  bloc: ^8.0.2
  copy_with_extension: ^2.0.2
  mongo_dart: ^0.7.4
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.1.7
  copy_with_extension_gen: ^2.0.3
  lints: ^1.0.0
  test: ^1.20.1
